language: python

matrix:
    include:
        - os: linux
          python: 3.5
          env: TOXENV=py35
        - os: linux
          python: 3.6
          env: TOXENV=py36
        - os: linux
          python: 3.7
          env: TOXENV=py37
        - os: osx
          language: generic
          env: TOXENV=py35
        - os: osx
          language: generic
          env: TOXENV=py36
         - os: osx
          language: generic
          env: TOXENV=py37
install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pip install .
script:
- pytest histogram
branch: master