matrix:
  include:
    - os: linux
      language: python
      python: 3.5
    - os: linux
      language: python
      python: 3.6
    - os: linux
      language: python
      python: 3.7
    - os: osx
      language: python
      python: 3.5
    - os: osx
      language: python
      python: 3.6
    - os: osx
      language: python
      python: 3.7

install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pip install .

script:
- pytest histogram

branch: master