language: generic

matrix:
    include:
        - os: linux
          python: 3.5
        - os: linux
          python: 3.6
        - os: linux
          python: 3.7
        - os: osx
          python: 3.5
        - os: osx
          python: 3.6
        - os: osx
          python: 3.7
install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pip install .
script:
- pytest histogram
branch: master